import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  exercicioHeader: {
    marginBottom: 12,
  },
  exercicioTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  exercicioNome: {
    fontSize: 17,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: -0.3,
    marginBottom: 2,
  },
  recordeBadge: {
    backgroundColor: colors.secondary,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  recordeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 1,
  },
  grupoMuscularText: {
    fontSize: 11,
    color: colors.terciary,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  descricaoText: {
    fontSize: 14,
    color: '#ccc',
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  historicoSection: {
    marginBottom: 16,
  },
  destaquesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
  },
  destaqueBox: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  destaqueLabel: {
    fontSize: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#383838',
  },
  recordeValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.secondary,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  ultimoDadoValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  divider: {
    height: 1,
    backgroundColor: '#383838',
    marginVertical: 10,
  },
  gridScreen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.textLight,
    textAlign: 'center',
    marginVertical: 24,
  },
  gridButton: {
    flex: 1,
    margin: 8,
    aspectRatio: 1,
    backgroundColor: colors.inputBackground,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  gridButtonInner: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  gridButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 8,
  },
  listHeader: {
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: colors.background,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    paddingVertical: 5,
  },
  backButtonText: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: '700',
  },
  // Chip row (filter bar)
  chipRow: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    paddingTop: 4,
    alignItems: 'center',
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  chipAtivo: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  chipInativo: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderColor: colors.inputBorder,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.terciary,
  },
  chipTextAtivo: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  // New card layout
  cardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 12,
  },
  iconBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  exercicioInfo: {
    flex: 1,
  },
  viewHistoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.secondary,
    marginTop: 12,
  },
  viewHistoryText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  possuiVariacoesLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.terciary,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginVertical: 8,
  },
});
