import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  exercicioHeader: {
    marginBottom: 12,
  },
  exercicioNome: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textLight,
    letterSpacing: -0.3,
    marginBottom: 2,
  },
  recordeBadge: {
    backgroundColor: colors.secondary,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  recordeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.textLight,
    letterSpacing: 1,
  },
  grupoMuscularText: {
    fontSize: 11,
    color: colors.terciary,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  destaquesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
  },
  destaqueBox: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  destaqueLabel: {
    fontSize: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.inputBorder,
  },
  recordeValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.secondary,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  ultimoDadoValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textLight,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.textLight,
    textAlign: 'center',
    marginVertical: 24,
  },
  listHeader: {
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: colors.background,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    paddingVertical: 5,
  },
  backButtonText: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: '700',
  },
  // Chip row (filter bar)
  chipScroll: {
    flexGrow: 0,
    flexShrink: 0,
  },
  chipRow: {
    paddingHorizontal: 16,
    paddingBottom: 4,
    paddingTop: 0,
    alignItems: 'center',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  chipAtivo: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  chipInativo: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderColor: colors.inputBorder,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.terciary,
  },
  chipTextAtivo: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textLight,
  },
  // New card layout
  cardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 12,
  },
  iconBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  exercicioInfo: {
    flex: 1,
  },
  viewHistoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.secondary,
    marginTop: 12,
  },
  viewHistoryText: {
    color: colors.textLight,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  possuiVariacoesLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.terciary,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginVertical: 8,
  },
  nomeBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 2,
  },
  padraoBadge: {
    backgroundColor: 'rgba(240, 192, 64, 0.15)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: 'rgba(240, 192, 64, 0.4)',
  },
  padraoBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#f0c040',
    letterSpacing: 0.5,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  formContent: {
    flex: 1,
    padding: 20,
    paddingBottom: 16,
  },
  requiredNote: {
    fontSize: 12,
    color: '#777',
    marginBottom: 20,
  },
  fieldContainer: {
    marginBottom: 4,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 6,
  },
  segmentedRow: {
    flexDirection: 'row',
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  segmentedButtonWrapper: {
    flex: 1,
  },
  segmentedButton: {
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentedButtonActive: {
    backgroundColor: colors.secondary,
  },
  segmentedButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.placeholderText,
  },
  segmentedButtonTextActive: {
    color: colors.textLight,
  },
  inputGroup: {
    flex: 1,
  },
  screenFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.primary,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  formBackButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formBackButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  saveButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  listContent: {
    padding: 16,
    paddingBottom: 8,
  },
  footer: {
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.primary,
    backgroundColor: colors.background,
  },
  footerBackButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBackButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  footerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  finalizeButton: {
    flex: 1,
    backgroundColor: colors.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finalizeButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  finalizeButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
});
