import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  listContent: {
    paddingBottom: 20,
  },
  chipRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  chipActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.placeholderText,
  },
  chipTextActive: {
    color: colors.textLight,
  },
  treinoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    overflow: 'hidden',
    paddingVertical: 14,
    paddingRight: 14,
    gap: 12,
  },
  treinoAccentBar: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 4,
  },
  treinoAccentBarAtivo: {
    backgroundColor: colors.success,
  },
  treinoAccentBarInativo: {
    backgroundColor: colors.danger,
  },
  chipIconLeft: {
    marginLeft: 4,
  },
  chipIconRight: {
    marginRight: 4,
  },
  treinoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  treinoInfo: {
    flex: 1,
  },
  treinoNomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  treinoNome: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textLight,
    marginBottom: 3,
  },
  treinoData: {
    fontSize: 12,
    color: '#777',
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    marginBottom: 16,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  fieldContainer: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 8,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  counterBadge: {
    backgroundColor: colors.secondary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  counterBadgeText: {
    color: colors.textLight,
    fontSize: 12,
    fontWeight: '700',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  exerciseItemSelected: {
    borderColor: colors.secondary,
    backgroundColor: 'rgba(255, 85, 85, 0.08)',
  },
  exerciseItemText: {
    flex: 1,
    fontSize: 14,
    color: colors.textMuted,
    fontWeight: '500',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.primary,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  saveButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  chipScrollContainer: {
    marginBottom: 10,
  },
  chipScrollRow: {
    gap: 8,
    alignItems: 'center',
    paddingVertical: 4,
  },
  fabRow: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  importarFabButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  qrContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  qrBox: {
    alignItems: 'center',
    padding: 28,
    marginHorizontal: 20,
    marginTop: 24,
    backgroundColor: colors.inputBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    gap: 18,
  },
  qrLabel: {
    fontSize: 13,
    color: colors.placeholderText,
    marginBottom: 2,
  },
  tokenDisplay: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  tokenText: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 6,
    color: colors.textLight,
  },
  expiracaoText: {
    fontSize: 13,
    color: '#888',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 20,
    marginTop: 20,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.inputBackground,
  },
  actionButtonPrimary: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textMuted,
  },
  actionButtonTextLight: {
    color: colors.textLight,
  },
  tabRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    gap: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  tabButtonActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.placeholderText,
  },
  tabButtonTextActive: {
    color: colors.textLight,
  },
  previewCard: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    padding: 16,
    gap: 10,
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.placeholderText,
    marginBottom: 4,
  },
  previewNomeInput: {
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
    color: colors.textMuted,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  previewExerciseItem: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.primary,
  },
  previewExerciseText: {
    color: '#ccc',
    fontSize: 14,
  },
  importButton: {
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
  },
  importButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  scannerAbaContainer: {
    alignItems: 'center',
    padding: 24,
  },
  chipIcon: {
    marginRight: 6,
  },
  manualAbaContainer: {
    padding: 20,
  },
  buscarButton: {
    marginHorizontal: 0,
    marginTop: 12,
  },
  previewTitleSpaced: {
    marginTop: 8,
  },
  previewExpiraText: {
    color: colors.textHint,
    fontSize: 12,
    marginTop: 8,
  },
});
