import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  listContent: {
    paddingBottom: 20,
  },
  chipRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#383838',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  chipActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#aaa',
  },
  chipTextActive: {
    color: '#fff',
  },
  treinoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#383838',
    overflow: 'hidden',
    paddingVertical: 14,
    paddingRight: 14,
    gap: 12,
  },
  treinoAccentBarAtivo: {
    backgroundColor: '#28a745',
  },
  treinoAccentBarInativo: {
    backgroundColor: '#dc3545',
  },
  treinoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  treinoInfo: {
    flex: 1,
  },
  treinoNomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  treinoNome: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textLight,
    marginBottom: 3,
  },
  treinoData: {
    fontSize: 12,
    color: '#777',
  },
  treinoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  treinoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a2a2a',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#383838',
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
  },
  situacaoIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  situacaoAtiva: {
    backgroundColor: '#4CAF50',
  },
  situacaoInativa: {
    backgroundColor: '#F44336',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#383838',
    marginBottom: 16,
  },
  checkboxLabel: {
    marginLeft: 12,
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '500',
  },
  selectedExercisesContainer: {
    marginTop: 10,
    flex: 1,
    marginBottom: 1,
  },
  selectedExercicioList: {
    height: '70%',
  },
  selectedExerciseItem: {
    backgroundColor: colors.inputBackground,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: colors.secondary,
  },
  selectedExerciseText: {
    color: colors.textLight,
    fontSize: 16,
  },
  selectedExercisesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: 8,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#222',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  fieldContainer: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e8e8e8',
    marginBottom: 8,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  counterBadge: {
    backgroundColor: colors.secondary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  counterBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#2a2a2a',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#383838',
  },
  exerciseItemSelected: {
    borderColor: colors.secondary,
    backgroundColor: 'rgba(255, 85, 85, 0.08)',
  },
  exerciseItemText: {
    flex: 1,
    fontSize: 14,
    color: '#e8e8e8',
    fontWeight: '500',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: '#222',
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#28a745',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: '#555',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  chipScrollContainer: {
    marginBottom: 10,
  },
  chipScrollRow: {
    gap: 8,
    alignItems: 'center',
    paddingVertical: 4,
  },
  fabRow: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  importarFabButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#383838',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  chipImportar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#383838',
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginLeft: 'auto',
  },
  qrContainer: {
    flex: 1,
    backgroundColor: '#222',
  },
  qrBox: {
    alignItems: 'center',
    padding: 28,
    marginHorizontal: 20,
    marginTop: 24,
    backgroundColor: '#2a2a2a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#383838',
    gap: 18,
  },
  qrLabel: {
    fontSize: 13,
    color: '#aaa',
    marginBottom: 2,
  },
  tokenDisplay: {
    backgroundColor: '#333',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  tokenText: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 6,
    color: '#fff',
  },
  expiracaoText: {
    fontSize: 13,
    color: '#888',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 20,
    marginTop: 20,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    backgroundColor: '#2a2a2a',
  },
  actionButtonPrimary: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#e8e8e8',
  },
  tabRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    gap: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#383838',
  },
  tabButtonActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#aaa',
  },
  tabButtonTextActive: {
    color: '#fff',
  },
  scannerContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
  },
  scannerCamera: {
    flex: 1,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerTarget: {
    width: 220,
    height: 220,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 12,
  },
  previewCard: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: '#2a2a2a',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#383838',
    padding: 16,
    gap: 10,
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#aaa',
    marginBottom: 4,
  },
  previewNomeInput: {
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
    color: '#e8e8e8',
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  previewExerciseItem: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  previewExerciseText: {
    color: '#ccc',
    fontSize: 14,
  },
  importButton: {
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
  },
  importButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
});
