import { StyleSheet } from 'react-native';
import { colors } from '../../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 30,
    minHeight: 80,
  },
  headerViewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerEditContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  userNameText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  inputNome: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    borderBottomWidth: 2,
    borderBottomColor: '#E53935',
    flex: 1,
    paddingBottom: 4,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    gap: 6,
  },
  editButtonText: {
    color: '#E53935',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    padding: 8,
  },
  cancelButtonText: {
    color: '#B0B0B0',
    fontSize: 16,
  },
  card: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 20,
    padding: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  separator: {
    height: 1,
    backgroundColor: '#48484A',
    marginVertical: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
  },
  genderSelector: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  genderButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#48484A',
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderButtonSelected: {
    backgroundColor: '#E53935',
    borderColor: '#E53935',
  },
  genderButtonText: {
    color: '#B0B0B0',
    fontWeight: 'bold',
  },
  genderButtonTextSelected: {
    color: '#FFFFFF',
  },
  actionButtonContainer: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: colors.background,
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: colors.background,
  },
  loginLogoSection: {
    alignItems: 'center',
    marginBottom: 36,
    marginTop: 16,
  },
  loginLogoTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.5,
    marginTop: 12,
    marginBottom: 4,
  },
  loginLogoSubtitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#888',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  loginInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderWidth: 1.5,
    borderColor: '#383838',
    borderRadius: 14,
    height: 52,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  loginInputRowFocused: {
    borderColor: colors.secondary,
  },
  loginInputIcon: {
    marginRight: 10,
  },
  loginInputText: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
  },
  loginEsqueciRow: {
    alignItems: 'flex-end',
    marginBottom: 20,
    marginTop: -4,
  },
  loginEsqueciText: {
    color: '#7aa9ff',
    fontSize: 13,
    fontWeight: '600',
    backgroundColor: 'rgba(37,99,235,0.10)',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  loginEntrarButton: {
    backgroundColor: colors.secondary,
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  loginEntrarButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  loginSeparatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  loginLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#383838',
    marginHorizontal: 10,
  },
  loginSeparatorText: {
    color: '#777',
    fontSize: 12,
    fontWeight: '700',
  },
  loginCadastrarButton: {
    borderWidth: 1,
    borderColor: '#383838',
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  loginCadastrarButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  loginCadastroButton: {
    backgroundColor: colors.secondary,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 20,
  },
  loginCadastroButtonText: {
    color: colors.buttonText,
    fontWeight: 'bold',
  },
  loginContainerEsqueciSenha: {
    alignItems: 'center',
    marginTop: 8,
  },
  loginBotoesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  cadastroFormAdminContainer: {
    marginTop: '10%',
  },
  cadastroFormImagePickerContainer: {
    alignItems: 'center',
  },
  cadastroFormiImageDescription: {
    marginTop: 5,
    color: '#666',
  },
  fieldContainer: {
    marginBottom: 16,
  },

  // ── Cadastro redesign ─────────────────────────────────────────────────────
  cadastroScrollContent: {
    flexGrow: 1,
    padding: 22,
    paddingBottom: 16,
    backgroundColor: colors.background,
  },
  cadastroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.5,
    marginTop: 8,
  },
  cadastroSubtitle: {
    fontSize: 13,
    color: '#aaa',
    marginTop: 6,
    marginBottom: 22,
    lineHeight: 18,
  },
  cadastroAvatarSection: {
    alignItems: 'center',
    marginBottom: 22,
  },
  cadastroAvatarWrapper: {
    width: 108,
    height: 108,
    borderRadius: 54,
    overflow: 'hidden',
    backgroundColor: '#2f2f2f',
    borderWidth: 2,
    borderColor: '#3a3a3a',
    borderStyle: 'dashed',
  },
  cadastroAvatarEditBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.background,
  },
  cadastroAvatarLabel: {
    fontSize: 12,
    color: '#aaa',
    marginTop: 10,
  },
  cadastroFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e8e8e8',
    marginBottom: 8,
  },
  cadastroRequired: {
    color: colors.secondary,
  },
  cadastroHint: {
    fontSize: 12,
    color: '#aaa',
    marginTop: -8,
    marginBottom: 14,
    paddingLeft: 4,
  },
  cadastroStrengthContainer: {
    marginTop: -8,
    marginBottom: 14,
  },
  cadastroStrengthRow: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 6,
  },
  cadastroStrengthSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },
  cadastroStrengthLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  cadastroOptionalRow: {
    flexDirection: 'row',
    gap: 10,
  },
  cadastroOptionalField: {
    flex: 1,
  },
  cadastroCompactInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderWidth: 1.5,
    borderColor: '#383838',
    borderRadius: 14,
    height: 50,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  cadastroCompactInputRowFocused: {
    borderColor: colors.secondary,
  },
  cadastroCompactInputText: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
  },
  cadastroGenderSelector: {
    flexDirection: 'row',
    gap: 8,
    height: 50,
    marginBottom: 14,
  },
  cadastroFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: colors.background,
  },
  cadastroVoltarButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cadastroVoltarButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  cadastroCadastrarButton: {
    flex: 2,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  cadastroCadastrarButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  cadastroCadastrarDisabled: {
    backgroundColor: '#555',
    shadowOpacity: 0,
    elevation: 0,
  },
  cadastroJaTemConta: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 13,
    color: '#aaa',
  },
  cadastroEntrarLink: {
    color: colors.secondary,
    fontWeight: '700',
  },

  // ── Perfil (visualization) ────────────────────────────────────────────────
  perfilScrollContent: {
    padding: 16,
    paddingBottom: 50,
  },
  avatarCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#333',
    padding: 22,
    marginBottom: 14,
    alignItems: 'center',
    shadowColor: '#ff5555',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 22,
    elevation: 6,
  },
  avatarImage: {
    width: 96,
    height: 96,
    borderRadius: 48,
    marginBottom: 14,
  },
  avatarGradient: {
    width: 96,
    height: 96,
    borderRadius: 48,
    marginBottom: 14,
    backgroundColor: '#ff5555',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontSize: 36,
    fontWeight: '800',
    color: '#fff',
  },
  nomeText: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textLight,
  },
  subtitleText: {
    fontSize: 13,
    color: colors.terciary,
    marginTop: 4,
  },
  infoCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#333',
    padding: 16,
    marginBottom: 14,
  },
  infoCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textLight,
    marginBottom: 12,
  },
  infoRowRead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a2a',
  },
  infoRowReadLast: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  infoIcon: {
    marginRight: 12,
  },
  infoLabel: {
    color: colors.terciary,
    fontSize: 13,
  },
  infoValue: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  menuRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.textLight,
  },
  menuRowLabelDanger: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.danger,
  },

  // ── Canonical form pattern ────────────────────────────────────────────────
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  formDescription: {
    fontSize: 13,
    color: '#aaa',
    marginBottom: 12,
    lineHeight: 20,
  },
  requiredNote: {
    fontSize: 12,
    color: '#777',
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e8e8e8',
    marginBottom: 6,
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: '#555',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },

  // ── Avatar picker for EditarPerfil ────────────────────────────────────────
  editarPerfilAvatarSection: {
    alignItems: 'center',
    marginBottom: 22,
  },
  editarPerfilAvatarWrapper: {
    width: 108,
    height: 108,
    borderRadius: 54,
    overflow: 'hidden',
    backgroundColor: '#2f2f2f',
    borderWidth: 2,
    borderColor: '#3a3a3a',
    borderStyle: 'dashed',
  },

  // ── EsqueciMinhaSenha redesign ────────────────────────────────────────────
  esqueciScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
    paddingBottom: 40,
    backgroundColor: colors.background,
  },
  esqueciIconSection: {
    alignItems: 'center',
    marginBottom: 22,
    marginTop: 12,
  },
  esqueciIconWrapper: {
    width: 76,
    height: 76,
    borderRadius: 20,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#383838',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
    marginBottom: 14,
  },
  esqueciTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.5,
  },
  esqueciSubtitle: {
    fontSize: 13,
    color: '#aaa',
    marginTop: 6,
    marginBottom: 22,
    lineHeight: 18,
  },
  esqueciFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 22,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  esqueciVoltarButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  esqueciVoltarButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  esqueciAltButton: {
    flex: 2,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  esqueciAltButtonDisabled: {
    backgroundColor: '#555',
    shadowOpacity: 0,
    elevation: 0,
  },
  esqueciAltButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },

  // ── Placeholder card ──────────────────────────────────────────────────────
  placeholderContent: {
    flex: 1,
  },
  placeholderCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#333',
    padding: 22,
    margin: 16,
    alignItems: 'center',
  },
  placeholderText: {
    fontSize: 14,
    color: colors.terciary,
    textAlign: 'center',
    lineHeight: 20,
  },
});
