import { StyleSheet } from 'react-native';
import { colors } from '../../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 30,
    minHeight: 80,
  },
  cancelButton: {
    padding: 8,
  },
  card: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 20,
    padding: 16,
  },
  separator: {
    height: 1,
    backgroundColor: '#48484A',
    marginVertical: 12,
  },
  genderSelector: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
    marginBottom: 4,
  },
  genderButtonWrapper: {
    flex: 1,
  },
  genderButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderButtonSelected: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  genderButtonText: {
    color: colors.terciary,
    fontSize: 14,
    fontWeight: '600',
  },
  genderButtonTextSelected: {
    color: colors.textLight,
    fontWeight: '700',
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: colors.background,
  },
  loginLogoSection: {
    alignItems: 'center',
    marginBottom: 36,
    marginTop: 16,
  },
  loginLogoTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.textLight,
    letterSpacing: -0.5,
    marginTop: 12,
    marginBottom: 4,
  },
  loginLogoSubtitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#888',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  loginInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderWidth: 1.5,
    borderColor: colors.inputBorder,
    borderRadius: 14,
    height: 52,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  loginInputRowFocused: {
    borderColor: colors.secondary,
  },
  loginInputIcon: {
    marginRight: 10,
  },
  loginInputText: {
    flex: 1,
    color: colors.textLight,
    fontSize: 16,
  },
  loginEsqueciRow: {
    alignItems: 'flex-end',
    marginBottom: 20,
    marginTop: -4,
  },
  loginEsqueciText: {
    color: '#7aa9ff',
    fontSize: 13,
    fontWeight: '600',
    backgroundColor: 'rgba(37,99,235,0.10)',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  loginEntrarButton: {
    backgroundColor: colors.secondary,
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  loginEntrarButtonText: {
    color: colors.textLight,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  loginSeparatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  loginLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.inputBorder,
    marginHorizontal: 10,
  },
  loginSeparatorText: {
    color: '#777',
    fontSize: 12,
    fontWeight: '700',
  },
  loginCadastrarButton: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  loginCadastrarButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  fieldContainer: {
    marginBottom: 16,
  },

  // ── Cadastro redesign ─────────────────────────────────────────────────────
  cadastroScrollView: {
    flex: 1,
  },
  cadastroScrollContent: {
    padding: 22,
    paddingBottom: 16,
    backgroundColor: colors.background,
  },
  cadastroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.textLight,
    letterSpacing: -0.5,
    marginTop: 8,
  },
  cadastroSubtitle: {
    fontSize: 13,
    color: colors.placeholderText,
    marginTop: 6,
    marginBottom: 22,
    lineHeight: 18,
  },
  cadastroAvatarSection: {
    alignItems: 'center',
    marginBottom: 22,
  },
  cadastroAvatarWrapper: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
  },
  cadastroAvatarEditBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.background,
  },
  cadastroAvatarLabel: {
    fontSize: 12,
    color: colors.placeholderText,
    marginTop: 10,
  },
  cadastroFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 8,
  },
  cadastroRequired: {
    color: colors.secondary,
  },
  cadastroHint: {
    fontSize: 12,
    color: colors.placeholderText,
    marginTop: -8,
    marginBottom: 14,
    paddingLeft: 4,
  },
  cadastroStrengthContainer: {
    marginTop: -8,
    marginBottom: 14,
  },
  cadastroStrengthRow: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 6,
  },
  cadastroStrengthSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },
  cadastroStrengthLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  cadastroOptionalRow: {
    flexDirection: 'row',
    gap: 10,
  },
  cadastroOptionalField: {
    flex: 1,
  },
  cadastroCompactInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderWidth: 1.5,
    borderColor: colors.inputBorder,
    borderRadius: 14,
    height: 50,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  cadastroCompactInputRowFocused: {
    borderColor: colors.secondary,
  },
  cadastroCompactInputText: {
    flex: 1,
    color: colors.textLight,
    fontSize: 14,
  },
  cadastroGenderSelector: {
    flexDirection: 'row',
    gap: 8,
    height: 50,
    marginBottom: 14,
  },
  cadastroTitleWrapper: {
    paddingHorizontal: 22,
    paddingTop: 8,
  },
  backButtonWrapper: {},
  saveButtonWrapper: {
    flex: 1,
  },
  cadastroJaTemConta: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 13,
    color: colors.placeholderText,
  },
  cadastroEntrarLink: {
    color: colors.secondary,
    fontWeight: '700',
  },

  // ── Perfil (visualization) ────────────────────────────────────────────────
  perfilScrollContent: {
    padding: 16,
    paddingBottom: 50,
  },
  avatarCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: 22,
    marginBottom: 14,
    alignItems: 'center',
    shadowColor: colors.secondary,
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 22,
    elevation: 6,
  },
  avatarImage: {
    width: 96,
    height: 96,
    borderRadius: 48,
    marginBottom: 14,
  },
  avatarGradient: {
    width: 96,
    height: 96,
    borderRadius: 48,
    marginBottom: 14,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontSize: 36,
    fontWeight: '800',
    color: colors.textLight,
  },
  nomeText: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textLight,
  },
  subtitleText: {
    fontSize: 13,
    color: colors.terciary,
    marginTop: 4,
  },
  infoCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: 16,
    marginBottom: 14,
  },
  infoCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textLight,
    marginBottom: 12,
  },
  infoRowRead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.inputBackground,
  },
  infoRowReadLast: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  infoIcon: {
    marginRight: 12,
  },
  infoLabel: {
    color: colors.terciary,
    fontSize: 13,
  },
  infoValue: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  menuRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.textLight,
  },
  menuRowLabelDanger: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.danger,
  },

  // ── Canonical form pattern ────────────────────────────────────────────────
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  formDescription: {
    fontSize: 13,
    color: colors.placeholderText,
    marginBottom: 12,
    lineHeight: 20,
  },
  requiredNote: {
    fontSize: 12,
    color: '#777',
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 6,
  },
  screenFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.primary,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  saveButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },

  // ── Avatar picker for EditarPerfil ────────────────────────────────────────
  editarPerfilAvatarSection: {
    alignItems: 'center',
    marginBottom: 22,
  },
  editarPerfilAvatarWrapper: {
    width: 108,
    height: 108,
    borderRadius: 54,
    overflow: 'hidden',
    backgroundColor: '#2f2f2f',
    borderWidth: 2,
    borderColor: colors.borderSubtle,
    borderStyle: 'dashed',
  },

  safeAreaBackground: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loginLogoTitleAccent: {
    color: '#FF5E2C',
  },
  positionRelative: {
    position: 'relative',
  },
  flexOne: {
    flex: 1,
  },
  flexOneRadius: {
    flex: 1,
    borderRadius: 14,
  },
  strengthSegmentEmpty: {
    backgroundColor: '#2f2f2f',
  },
  // ── EsqueciMinhaSenha redesign ────────────────────────────────────────────
  esqueciScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
    paddingBottom: 40,
    backgroundColor: colors.background,
  },
  esqueciIconSection: {
    alignItems: 'center',
    marginBottom: 22,
    marginTop: 12,
  },
  esqueciIconWrapper: {
    width: 76,
    height: 76,
    borderRadius: 20,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
    marginBottom: 14,
  },
  esqueciTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.textLight,
    letterSpacing: -0.5,
  },
  esqueciSubtitle: {
    fontSize: 13,
    color: colors.placeholderText,
    marginTop: 6,
    marginBottom: 22,
    lineHeight: 18,
  },
  // ── Placeholder card ──────────────────────────────────────────────────────
  placeholderContent: {
    flex: 1,
  },
  placeholderCard: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: 22,
    margin: 16,
    alignItems: 'center',
  },
  placeholderText: {
    fontSize: 14,
    color: colors.terciary,
    textAlign: 'center',
    lineHeight: 20,
  },
});
