import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  cardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#262626',
    borderRadius: 16,
    marginVertical: 6,
    padding: 14,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
    position: 'relative',
  },
  stripe: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: '#ff5555',
  },
  iconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#2f2f2f',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  nomeText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    paddingLeft: 12,
  },
  fieldContainer: {
    marginBottom: 4,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e8e8e8',
    marginBottom: 6,
  },
  formDescription: {
    fontSize: 13,
    color: '#aaa',
    marginBottom: 12,
    lineHeight: 20,
  },
  requiredNote: {
    fontSize: 12,
    color: '#777',
    marginBottom: 20,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#222',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 16,
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: '#222',
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#28a745',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    backgroundColor: '#555',
  },
  saveButtonIcon: {
    lineHeight: 18,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
});
