import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  listContent: {
    paddingBottom: 20,
  },
  sectionHeader: {
    backgroundColor: '#2a2a2a',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 999,
    marginTop: 15,
    marginBottom: 8,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#383838',
  },
  sectionHeaderText: {
    color: colors.textLight,
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  destaquesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  destaqueBox: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  destaqueLabel: {
    fontSize: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  destaqueValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#383838',
  },
  observacaoText: {
    fontSize: 12,
    color: colors.terciary,
    fontStyle: 'italic',
    marginTop: 12,
    textAlign: 'center',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: '#222',
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  addButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.secondary,
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
});
