import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';

export default StyleSheet.create({
  listContent: {
    paddingBottom: 20,
  },
  sectionHeader: {
    backgroundColor: '#2a2a2a',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 999,
    marginTop: 15,
    marginBottom: 8,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#383838',
  },
  sectionHeaderText: {
    color: colors.textLight,
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  destaquesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  destaqueBox: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  destaqueLabel: {
    fontSize: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  destaqueValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#383838',
  },
  observacaoText: {
    fontSize: 12,
    color: colors.terciary,
    fontStyle: 'italic',
    marginTop: 12,
    textAlign: 'center',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#333',
    backgroundColor: '#222',
    alignItems: 'center',
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  addButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.secondary,
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  selecionarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(240, 192, 64, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(240, 192, 64, 0.3)',
  },
  selecionarButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#f0c040',
    letterSpacing: 0.3,
  },
  selecaoInfoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 85, 85, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 85, 85, 0.3)',
  },
  selecaoInfoText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.secondary,
  },
  cancelarSelecaoText: {
    fontSize: 13,
    color: '#aaa',
    fontWeight: '600',
  },
  cancelarSelecaoButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelarSelecaoButtonText: {
    color: '#e8e8e8',
    fontSize: 15,
    fontWeight: '600',
  },
  moverButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f0a000',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  moverButtonDisabled: {
    backgroundColor: '#555',
  },
  moverButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  registroSelecionadoContainer: {
    backgroundColor: 'rgba(240, 160, 0, 0.1)',
    borderColor: 'rgba(240, 160, 0, 0.4)',
  },
  selecaoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selecaoItemContent: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#2a2a2a',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 36,
    paddingHorizontal: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#383838',
  },
  modalItemText: {
    fontSize: 15,
    color: '#e8e8e8',
    fontWeight: '600',
  },
  modalCancelar: {
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  modalCancelarText: {
    fontSize: 15,
    color: '#aaa',
    fontWeight: '600',
  },
});
