import { StyleSheet } from 'react-native';
import { colors } from '../../../components/Styles/ComumStyles';
import { BANNER_HEIGHT } from '../../../comum/constants';

export default StyleSheet.create({
  listContent: {
    paddingBottom: 20,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    color: colors.terciary,
    marginTop: 12,
    fontSize: 14,
    textAlign: 'center',
  },
  sectionHeader: {
    backgroundColor: colors.inputBackground,
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 999,
    marginTop: 15,
    marginBottom: 8,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  sectionHeaderText: {
    color: colors.textLight,
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  destaquesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  destaqueBox: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  destaqueLabel: {
    fontSize: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  destaqueValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textLight,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  statDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.inputBorder,
  },
  observacaoText: {
    fontSize: 12,
    color: colors.terciary,
    fontStyle: 'italic',
    marginTop: 12,
    textAlign: 'center',
  },
  formFooter: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: colors.primary,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  formFooterComBanner: {
    paddingBottom: BANNER_HEIGHT,
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  addButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.secondary,
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  addButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  selecionarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(240, 192, 64, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(240, 192, 64, 0.3)',
  },
  selecionarButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#f0c040',
    letterSpacing: 0.3,
  },
  selecaoInfoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 85, 85, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 85, 85, 0.3)',
  },
  selecaoInfoText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.secondary,
  },
  cancelarSelecaoText: {
    fontSize: 13,
    color: colors.placeholderText,
    fontWeight: '600',
  },
  cancelarSelecaoButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelarSelecaoButtonText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  moverButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f0a000',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  moverButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  moverButtonText: {
    color: colors.textLight,
    fontSize: 15,
    fontWeight: '700',
  },
  registroSelecionadoContainer: {
    backgroundColor: 'rgba(240, 160, 0, 0.1)',
    borderColor: 'rgba(240, 160, 0, 0.4)',
  },
  selecaoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selecaoItemContent: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: colors.inputBackground,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 36,
    paddingHorizontal: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textLight,
    marginBottom: 16,
    textAlign: 'center',
  },
  modalItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.inputBorder,
  },
  modalItemText: {
    fontSize: 15,
    color: colors.textMuted,
    fontWeight: '600',
  },
  modalCancelar: {
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  modalCancelarText: {
    fontSize: 15,
    color: colors.placeholderText,
    fontWeight: '600',
  },
  prCardDestaque: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    overflow: 'hidden',
    paddingTop: 10,
    paddingBottom: 4,
    paddingHorizontal: 12,
  },
  prCardBordaAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.secondary,
  },
  prCardDestaqueHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  prCardDestaqueTitulo: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.secondary,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    flex: 1,
  },
  prCardDestaqueData: {
    fontSize: 10,
    color: colors.terciary,
    fontWeight: '600',
  },
  prCardConteudo: {
    paddingVertical: 4,
  },
});
